// verbs.js
export const verbs = [
  {
    word: "Sprint",
    gujarati: "દોડવું",
    typeofWord: "Verb/Noun",
    meaning: "Move quickly",
    wordExample: {
      english: "The cat sprinted after the mouse, its claws extended and its eyes fixed on the fleeing prey.",
      gujarati: "બિલાડી ઉંદરની પાછળ દોડી, તેના પંજા લંબાવ્યા અને તેની આંખો ભાગી રહેલા શિકાર પર સ્થિર થઈ.",
    },
    synonyms: [
      { word: "jog", gujarati: "જોગિંગ કરવી" },
      { word: "run", gujarati: "દોડવું" },
      { word: "dash", gujarati: "ઝડપથી દોડવું" },
    ],
    antonyms: [
      { word: "stop", gujarati: "રોકવું" },
      { word: "halt", gujarati: "અટકવું" },
      { word: "cease", gujarati: "બંધ કરવું" },
    ],
  },
  {
    word: "Leap",
    gujarati: "છલાંગ મારવી",
    typeofWord: "Noun/Verb",
    meaning: "The act of moving suddenly upwards into the air by pushing off the ground with your feet.",
    wordExample: {
      english: "The scientist leaped to the conclusion that the new data supported their hypothesis, though further research was still needed.",
      gujarati: "વૈજ્ઞાનિક એ નિષ્કર્ષ પર કૂદકો માર્યો કે નવો ડેટા તેમની પૂર્વધારણાને સમર્થન આપે છે, જો કે હજુ વધુ સંશોધનની જરૂર હતી.",
    },
    synonyms: [
      { word: "Jump", gujarati: "કૂદવું" },
      { word: "bound", gujarati: "ઊંચાઈએ કૂદવું" },
      { word: "spring", gujarati: "છલોંગ મારવી" },
    ],
    antonyms: [
      { word: "fall", gujarati: "પડવું" },
      { word: "sink", gujarati: "ડૂબવું" },
      { word: "descend", gujarati: "ઊતરવું" },
    ],
  },
  {
    word: "Surreptitiously",
    gujarati: "ગુપ્ત રીતે",
    typeofWord: "Adjective  + ly = Adverb",
    meaning: "In a secretive manner, especially to avoid notice or attention.",
    wordExample: {
      english: "The spyware was surreptitiously installed on the phones of unsuspecting users.",
      gujarati: "આ સ્પાયવેર અસંદિગ્ધ (શંકાસ્પદ ના હોય તેવા) વપરાશકર્તાઓના ફોન પર ગુપ્ત રીતે ઇન્સ્ટોલ કરવામાં આવ્યું હતું.",
    },
    synonyms: [
      { word: "secretly", gujarati: "ગુપ્ત રીતે" },
      { word: "stealthily", gujarati: "ચોરીછૂપીથી" },
      { word: "covertly", gujarati: "ગુપ્ત રીતે" },
      { word: "clandestinely", gujarati: "ગુપ્ત રીતે" },
    ],
    antonyms: [
      { word: "openly", gujarati: "ખુલ્લેઆમ" },
      { word: "overtly", gujarati: "સ્પષ્ટપણે" },
      { word: "clearly", gujarati: "સ્પષ્ટપણે" },
      { word: "transparently", gujarati: "પારદર્શક રીતે" },
      { word: "ostensibly", gujarati: "દેખાવકારક રીતે" },
      { word: "conspicuously", gujarati: "દેખીતી રીતે" },
      { word: "evidently", gujarati: "દેખીતી રીતે" },
      { word: "apparently", gujarati: "દેખીતી રીતે" },
    ],
  },
  {
    word: "Obfuscation",
    gujarati: "અસ્પષ્ટતા / ભ્રમ ઉત્પન્ન કરવો / મૂંઝવણ",
    typeofWord: "Obfuscate  + ion = Noun",
    meaning: "The action of making something unclear of difficult to understand.",
    wordExample: {
      english: "The government's obfuscation on surveillance issues has raised concerns about accountability.",
      gujarati: "સર્વેલન્સના મુદ્દાઓ પર સરકારની મૂંઝવણને કારણે જવાબદારી અંગે ચિંતા વધી છે.",
    },
    synonyms: [
      { word: "confusion", gujarati: "મૂંઝવણ" },
      { word: "ambiguity", gujarati: "અસ્પષ્ટતા" },
      { word: "obscurity", gujarati: "અસ્પષ્ટતા" },
      { word: "complication", gujarati: "ગૂંચવણ" },
      { word: "vague", gujarati: "અસ્પષ્ટ" },
      { word: "equivocal", gujarati: "અસ્પષ્ટ" },
      { word: "marky", gujarati: "અસ્પષ્ટ/ચિહ્નિત" },
      { word: "implicit", gujarati: "અસ્પષ્ટ" },
    ],
    antonyms: [
      { word: "clarity", gujarati: "સ્પષ્ટતા" },
      { word: "transparency", gujarati: "પારદર્શિતા" },
      { word: "simplicity", gujarati: "સરળતા" },
      { word: "lucid", gujarati: "સ્પષ્ટ" },
      { word: "pellucid", gujarati: "તદન સ્પષ્ટ/સ્વચ્છ" },
      { word: "unequivocal", gujarati: "સ્પષ્ટ" },
      { word: "unambiguous", gujarati: "સ્પષ્ટ" },
      { word: "explicit", gujarati: "સ્પષ્ટ" },
    ],
  },
  {
    word: "Tempering",
    gujarati: "હસ્તક્ષેપ",
    typeofWord: "Verb",
    meaning: "The act of interfering with something to cause damage or alter its intended function.",
    wordExample: {
      english: "Allegations/Accusation of tampering with election machines have led to widespreat mistrust.",
      gujarati: "ચૂંટણી મશીનો સાથે છેડછાડના આક્ષેપો/આરોપથી વ્યાપક અવિશ્વાસ ફેલાયો છે.",
    },
    synonyms: [
      { word: "interference", gujarati: "દખલગીરી" },
      { word: "meddling", gujarati: "દખલગીરી" },
      { word: "manipulation", gujarati: "ચાલાકી" },
      { word: "sabotage", gujarati: "તોડફોડ" },
    ],
    antonyms: [
      { word: "preservation", gujarati: "જાળવણી" },
      { word: "safeguarding", gujarati: "રક્ષણ" },
      { word: "protection", gujarati: "રક્ષણ" },
      { word: "conservation", gujarati: "સંરક્ષણ" },
    ],
  },
  {
    word: "Jeopardize",
    gujarati: "જોખમમાં મૂકવું",
    typeofWord: "Verb",
    meaning: "To put something at risk of harm, loss, or failure.",
    wordExample: {
      english: "The government's silence on cybersecurity issues may jeopardize public trust.",
      gujarati: "સાયબર સુરક્ષા મુદ્દાઓ પર સરકારનું મૌન લોકોના વિશ્વાસને જોખમમાં મૂકી શકે છે.",
    },
    synonyms: [
      { word: "endanger", gujarati: "જોખમમાં મૂકવું" },
      { word: "threaten", gujarati: "ધમકી" },
      { word: "imperil", gujarati: "જોખમ" },
      { word: "compromise", gujarati: "સમાધાન" },
    ],
    antonyms: [
      { word: "protect", gujarati: "રક્ષણ" },
      { word: "safeguard", gujarati: "રક્ષણ" },
      { word: "secure", gujarati: "સુરક્ષિત" },
      { word: "bolster", gujarati: "મજબૂત" },
      { word: "reinforce", gujarati: "મજબૂત બનાવવું" },
      { word: "fortify", gujarati: "મજબૂત બનાવવું" },
    ],
  },
  {
    word: "Dissidents",
    gujarati: "અસંતુષ્ટ વ્યક્તિ",
    typeofWord: "Noun",
    meaning: "Individuals who disagree with or oppose an established policy or authority.",
    wordExample: {
      english: "Dissidents were allegedly targeted using surveillance software.",
      gujarati: "સર્વેલન્સ સોફ્ટવેરનો ઉપયોગ કરીને અસંતુષ્ટોને કથિત રીતે નિશાન બનાવવામાં આવ્યા હતા.",
    },
    synonyms: [
      { word: "protesters", gujarati: "વિરોધીઓ" },
      { word: "rebels", gujarati: "બળવાખોરો" },
      { word: "dissenters", gujarati: "મતભેદ" },
      { word: "oppositionists", gujarati: "વિરોધીઓ" },
    ],
    antonyms: [
      { word: "conformists", gujarati: "અનુરૂપ" },
      { word: "supporters", gujarati: "સમર્થકો" },
      { word: "loyalists", gujarati: "વફાદાર" },
    ],
  },
  {
    word: "Impetus",
    gujarati: "પ્રેરણા / પ્રોત્સાહન / ઉત્તેજના",
    typeofWord: "Noun",
    meaning: "A driving force or stimulus that encourages action or progress.",
    wordExample: {
      english: "The ruling provided new impetus to investigate allegation of spyware misuse.",
      gujarati: "આ ચુકાદાએ સ્પાયવેરના દુરુપયોગના આરોપની તપાસ માટે નવી પ્રેરણા પૂરી પાડી."
    },
    synonyms: [
      { word: "momentum", gujarati: "વેગ" },
      { word: "motivation", gujarati: "પ્રેરણા" },
      { word: "catalyst", gujarati: "ઉત્પ્રેરક" },
      { word: "incentive", gujarati: "પ્રોત્સાહન" },
    ],
    antonyms: [
      { word: "deterrent", gujarati: "અવરોધક" },
      { word: "hindrance", gujarati: "અવરોધ" },
      { word: "obstacle", gujarati: "અવરોધ" },
      { word: "halt", gujarati: "રોકવું" },
      { word: "prohibit", gujarati: "પ્રતિબંધિત" },
      { word: "proscribe", gujarati: "નિષેધ / પ્રતિબંધ મૂકવો" },
    ],
  },
  {
    word: "Draconian",
    gujarati: "કઠોર",
    typeofWord: "draconic + ian = Adjective",
    meaning: "Excessively harsh or severe.",
    wordExample: {
      english: "Critics labeled the new surveillance laws as draconian measures.",
      gujarati: "ટીકાકારોએ નવા સર્વેલન્સ કાયદાને કઠોર પગલાં તરીકે લેબલ કર્યા."
    },
    synonyms: [
      { word: "oppressive", gujarati: "દમનકારી" },
      { word: "authoritarian", gujarati: "સરમુખત્યારશાહી" },
      { word: "stringent", gujarati: "કડક" },
      { word: "harsh", gujarati: "કઠોર" },
    ],
    antonyms: [
      { word: "lenient", gujarati: "ઉદાર" },
      { word: "mild", gujarati: "હળવું" },
      { word: "permissive", gujarati: "પરવાનગી આપનારું" },
      { word: "flexible", gujarati: "લવચીક" },
    ],
  },
  {
    word: "Plausible",
    gujarati: "સંભવ / બુદ્ધિગમ્ય",
    typeofWord: "ible = Adjective",
    meaning: "Seeming reasonable or probable.",
    wordExample: {
      english: "The explanation provided by the officials seemed plausible at first glance.",
      gujarati: "અધિકારીઓ દ્વારા આપવામાં આવેલ ખુલાસો પ્રથમ નજરે વાજબી લાગતો હતો."
    },
    synonyms: [
      { word: "believable", gujarati: "વિશ્વાસપાત્ર" },
      { word: "credible", gujarati: "વિશ્વસનીય" },
      { word: "likely", gujarati: "શક્યતા" },
      { word: "feasible", gujarati: "શક્ય" },
      { word: "logical", gujarati: "તાર્કિક" },
      { word: "rational", gujarati: "તર્કસંગત" },
    ],
    antonyms: [
      { word: "implausible", gujarati: "અકલ્પ્ય" },
      { word: "unlikely", gujarati: "અસંભવિત" },
      { word: "improbable", gujarati: "અસંભવિત" },
      { word: "doubtful", gujarati: "શંકાસ્પદ" },
    ],
  },
  {
    word: "Repercussions",
    gujarati: "પરિણામ / પ્રત્યાઘાતો",
    typeofWord: "ion = Noun",
    meaning: "Unintended consequences or effects, often negative, of an action or event.",
    wordExample: {
      english: "The decision to restrict public access to poll documents may have severe repercussions.",
      gujarati: "મતદાન દસ્તાવેજોની જાહેર ઍક્સેસને પ્રતિબંધિત કરવાના નિર્ણયના ગંભીર પરિણામો આવી શકે છે."
    },
    synonyms: [
      { word: "consequences", gujarati: "પરિણામો" },
      { word: "outcomes", gujarati: "પરિણામો" },
      { word: "fallout", gujarati: "પડતી" },
      { word: "ramifications", gujarati: "અસર" },
    ],
    antonyms: [
      { word: "causes", gujarati: "કારણો" },
      { word: "antecedents", gujarati: "પૂર્વજો" },
      { word: "reasons", gujarati: "કારણો" },
    ],
  },
  {
    word: "Exacerbate",
    gujarati: "વધારવું / ખરાબ કરવું",
    typeofWord: "verb",
    meaning: "To make a problem or situation worse.",
    wordExample: {
      english: "The lack of transparency only serves to exacerbate public mistrust.",
      gujarati: "પારદર્શિતાનો અભાવ જનતાના અવિશ્વાસને વધારવાનું કામ કરે છે."
    },
    synonyms: [
      { word: "Aggravate", gujarati: "વધારવું" },
      { word: "Worsen", gujarati: "ખરાબ કરવું" },
      { word: "Intensify", gujarati: "તીવ્ર બનાવવું" },
      { word: "Heighten", gujarati: "ઉંચું ચઢાવવું" },
    ],
    antonyms: [
      { word: "Alleviate", gujarati: "ઘટાડવું" },
      { word: "Mitigate", gujarati: "ઘટાડવું" },
      { word: "Improve", gujarati: "સુધારવું" },
      { word: "Ease", gujarati: "સરળ બનાવવું" },
    ],
  },
  {
    word: "Stratified",
    gujarati: "સ્તરીકૃત / વિભાજિત",
    typeofWord: "adjective",
    meaning: "Divided into levels or layers, often socially or hierarchically.",
    wordExample: {
      english: "Relief efforts in India often reflect its stratified societal structure.",
      gujarati: "ભારતમાં રાહત કાર્યો ઘણીવાર તેની સ્તરીકૃત સામાજિક રચનાને પ્રતિબિંબિત કરે છે.",
    },
    synonyms: [
      { word: "Layered", gujarati: "સ્તરવાળું" },
      { word: "Tiered", gujarati: "સ્તરીબદ્ધ" },
      { word: "Hierarchical", gujarati: "પદાનુક્રમીય" },
    ],
    antonyms: [
      { word: "Equal", gujarati: "સમાન" },
      { word: "Unified", gujarati: "એકીકૃત" },
      { word: "Homogeneous", gujarati: "સજાતીય" },
    ],
  },
  {
    word: "Perfunctory",
    gujarati: "અવ્યવસ્થિત / બેદરકારીભર્યું / જેમ તેમ કરી નાંખેલું",
    typeofWord: "adjective",
    meaning: "Carried out with minimal effort or reflection; superficial.",
    wordExample: {
      english: "The perfunctory relief efforts in some regions left many affected people dissatisfied.",
      gujarati: "કેટલાક પ્રદેશોમાં અવ્યવસ્થિત રાહત પ્રયાસોએ ઘણા અસરગ્રસ્ત લોકોને અસંતુષ્ટ છોડી દીધા.",
    },
    synonyms: [
      { word: "Cursory", gujarati: "દોડધામવાળું" },
      { word: "Mechanical", gujarati: "યાંત્રિક" },
      { word: "Indifferent", gujarati: "ઉદાસીન" },
      { word: "Negligent", gujarati: "બેદરકારી" },
    ],
    antonyms: [
      { word: "Thorough", gujarati: "સંપૂર્ણ" },
      { word: "Meticulous", gujarati: "કાળજીપૂર્વક" },
      { word: "Diligent", gujarati: "પરિશ્રમી" },
      { word: "Attentive", gujarati: "ધ્યાન આપનાર" },
    ],
  },
  {
    word: "Inundation",
    gujarati: "પૂર / જળપ્રલય",
    typeofWord: "noun",
    meaning: "An overwhelming abundance of things or flooding of water.",
    wordExample: {
      english: "The tsunami caused an inundation that submerged entire villages.",
      gujarati: "સુનામીના કારણે આખા ગામો પાણીમાં ડૂબી ગયા હતા.",
    },
    synonyms: [
      { word: "Flood", gujarati: "પૂર" },
      { word: "Deluge", gujarati: "પ્રલય" },
      { word: "Overflow", gujarati: "ઉભરાવું" },
      { word: "Surge", gujarati: "છલોછલ" },
    ],
    antonyms: [
      { word: "Drought", gujarati: "દુષ્કાળ" },
      { word: "Scarcity", gujarati: "અછત" },
      { word: "Deficiency", gujarati: "કમી" },
    ],
  },
  {
    word: "Ostensible",
    gujarati: "દેખાવડું / દેખાવ પૂરતું",
    typeofWord: "adjective",
    meaning: "Appearing to be true but not necessarily so.",
    wordExample: {
      english: "The ostensible purpose of privatising beaches was tourism development, but it displaced communities.",
      gujarati: "સાગરકિનારાઓનું ખાનગીકરણ કરવાનો દેખાવડો હેતુ પ્રવાસન વિકાસ હતો, પરંતુ તેનાથી સમુદાયોનું વિસ્થાપન થયું.",
    },
    synonyms: [
      { word: "Apparent", gujarati: "દેખીતું" },
      { word: "Superficial", gujarati: "સપાટીદર્શી" },
      { word: "Seeming", gujarati: "લાગતું / દેખાતું / અવાસ્તવિક" },
      { word: "Outward", gujarati: "બાહ્ય" },
    ],
    antonyms: [
      { word: "Genuine", gujarati: "ખરું / સાચું / અસલી" },
      { word: "Real", gujarati: "વાસ્તવિક" },
      { word: "Actual", gujarati: "વાસ્તવિક" },
      { word: "True", gujarati: "સાચું" },
    ],
  },
  {
    word: "Deleterious",
    gujarati: "હાનિકારક",
    typeofWord: "adjective",
    meaning: "Causing harm or damage.",
    wordExample: {
      english: "Shrimp farming has had deleterious effects on coastal ecosystems.",
      gujarati: "ઝીંગાના ખેતીએ દરિયાકાંઠાના પર્યાવરણ પર હાનિકારક અસરો કરી છે.",
    },
    synonyms: [
      { word: "Harmful", gujarati: "હાનિકારક" },
      { word: "Detrimental", gujarati: "હાનિકારક" },
      { word: "Injurious", gujarati: "હાનિકારક" },
      { word: "Adverse", gujarati: "પ્રતિકૂળ" },
    ],
    antonyms: [
      { word: "Beneficial", gujarati: "લાભદાયક" },
      { word: "Advantageous", gujarati: "લાભદાયક" },
      { word: "Helpful", gujarati: "મદદરૂપ" },
      { word: "Salutary", gujarati: "લાભદાયક" },
    ],
  },
  {
    word: "Efficacy",
    gujarati: "કાર્યક્ષમતા / અસરકારકતા",
    typeofWord: "noun",
    meaning: "The ability to produce the desired result.",
    wordExample: {
      english: "The efficacy of disaster response teams was evident in their quick action.",
      gujarati: "આપત્તિ સંચાલન ટીમોની કાર્યક્ષમતા તેમની ઝડપી કાર્યવાહીમાં સ્પષ્ટ દેખાતી હતી.",
    },
    synonyms: [
      { word: "Effectiveness", gujarati: "અસરકારકતા" },
      { word: "Efficiency", gujarati: "કાર્યક્ષમતા" },
      { word: "Success", gujarati: "સફળતા" },
      { word: "Potency", gujarati: "શક્તિ" },
      { word: "Capability", gujarati: "ક્ષમતા" },
    ],
    antonyms: [
      { word: "Ineffectiveness", gujarati: "બિનઅસરકારકતા" },
      { word: "Inefficacy", gujarati: "બિનકાર્યક્ષમતા" },
      { word: "Failure", gujarati: "નિષ્ફળતા" },
      { word: "Ineptness", gujarati: "અયોગ્યતા" },
      { word: "Inadequacy", gujarati: "અપૂર્ણતા / અયોગ્યતા" },
    ],
  },
  {
    word: "Palliative",
    gujarati: "ઉપશામક / દર્દશામક / આરામ આપવા વાળું",
    typeofWord: "adjective",
    meaning: "Relieving pain or alleviating a problem without addressing the root cause.",
    wordExample: {
      english: "Constructing temporary shelters provided a palliative solution to the housing crisis post-tsunami.",
      gujarati: "કામચલાઉ આશ્રયસ્થાનો બાંધવાથી સુનામી પછીના આવાસ સંકટ માટે ઉપશામક ઉકેલ મળ્યો.",
    },
    synonyms: [
      { word: "Soothing", gujarati: "સુખદાયક" },
      { word: "Alleviating", gujarati: "ઘટાડનારું" },
      { word: "Mitigating", gujarati: "ઘટાડનારું" },
      { word: "Temporary relief", gujarati: "કામચલાઉ રાહત" },
    ],
    antonyms: [
      { word: "Exacerbating", gujarati: "વધારનારું" },
      { word: "Intensifying", gujarati: "તીવ્ર બનાવનારું" },
    ],
  },
  {
    word: "Impunity",
    gujarati: "દંડમુક્તિ / દંડથી છૂટ",
    typeofWord: "noun",
    meaning: "Exemption from punishment or harm.",
    wordExample: {
      english: "The corrupt officials believed they could operate with impunity, facing no consequences for their illegal actions.",
      gujarati: "ભ્રષ્ટ અધિકારીઓ માનતા હતા કે તેઓ તેમની ગેરકાયદેસર ક્રિયાઓ માટે કોઈ પરિણામ ભોગવતા નથી, તેઓ મુક્તિ સાથે કામ કરી શકે છે.",
    },
    synonyms: [
      { word: "Immunity", gujarati: "રોગપ્રતિકારકતા" },
      { word: "Exemption", gujarati: "છૂટ" },
      { word: "Protection", gujarati: "સુરક્ષા" },
      { word: "Indemnity", gujarati: "હાનિપૂર્તિ / નુકસાન સામે સલામતી" },
    ],
    antonyms: [
      { word: "Accountability", gujarati: "જવાબદારી" },
      { word: "Liability", gujarati: "દાયિત્વ" },
      { word: "Penalty", gujarati: "દંડ" },
      { word: "Culpability", gujarati: "દોષ" },
    ],
  },
  {
    word: "Recalcitrant",
    gujarati: "હઠીલા / જિદ્દી",
    typeofWord: "adjective",
    meaning: "Stubbornly resistant to authority or control.",
    wordExample: {
      english: "Recalcitrant attitudes towards environmental laws have hampered conservation efforts.",
      gujarati: "પર્યાવરણીય કાયદાઓ પ્રત્યેના હઠીલા વલણોએ સંરક્ષણ પ્રયાસોમાં અવરોધ ઊભો કર્યો છે.",
    },
    synonyms: [
      { word: "Defiant", gujarati: "વિરોધી / માથાભારે / ઉદ્ધત" },
      { word: "Uncooperative", gujarati: "અસહકારી" },
      { word: "Rebellious", gujarati: "બળવાખોર" },
      { word: "Obstinate", gujarati: "હઠીલા" },
    ],
    antonyms: [
      { word: "Compliant", gujarati: "આજ્ઞાકારી" },
      { word: "Obedient", gujarati: "આજ્ઞાકારી" },
      { word: "Submissive", gujarati: "વશીભૂત / આધીન" },
      { word: "Cooperative", gujarati: "સહકારી" },
    ],
  },
  {
    word: "Precarious",
    gujarati: "અસ્થિર / અનિશ્ચિત",
    typeofWord: "adjective",
    meaning: "Not securely held; dangerously likely to fall or collapse.",
    wordExample: {
      english: "The precarious condition of mangroves highlights the urgency for conservation.",
      gujarati: "મેન્ગ્રોવની અસ્થિર સ્થિતિ સંરક્ષણની તાત્કાલિક જરૂરિયાત પર પ્રકાશ પાડે છે.",
    },
    synonyms: [
      { word: "Unstable", gujarati: "અસ્થિર" },
      { word: "Insecure", gujarati: "અસુરક્ષિત" },
      { word: "Risky", gujarati: "જોખમી" },
      { word: "Uncertain", gujarati: "અનિશ્ચિત" },
    ],
    antonyms: [
      { word: "Stable", gujarati: "સ્થિર" },
      { word: "Secure", gujarati: "સુરક્ષિત" },
      { word: "Safe", gujarati: "સુરક્ષિત" },
      { word: "Firm", gujarati: "દૃઢ" },
    ],
  },
  {
    word: "Exert",
    gujarati: "શ્રમ / અમલમાં મૂકવું / પ્રભાવ પાડવો",
    typeofWord: "verb",
    meaning: "To apply or put forth effort, influence, or pressure.",
    wordExample: {
      english: "China exerts significant control over the global rare earth supply chain.",
      gujarati: "ચીન વિશ્વની દુર્લભ પૃથ્વી પુરવઠા શૃંખલા પર નોંધપાત્ર નિયંત્રણ લાદે છે.",
    },
    synonyms: [
      { word: "Apply", gujarati: "લાગુ કરવું" },
      { word: "Exercise", gujarati: "વ્યાયામ કરવો" },
      { word: "Wield", gujarati: "વપરાશ કરવો" },
      { word: "Enforce", gujarati: "લાગુ કરવું" },
    ],
    antonyms: [
      { word: "Withdraw", gujarati: "પાછો ખેંચવો" },
      { word: "Relax", gujarati: "આરામ કરવો" },
      { word: "Neglect", gujarati: "ઉપેક્ષા કરવી / અવગણના કરવી" },
      { word: "Cease", gujarati: "બંધ કરવો" },
    ],
  },
  {
    word: "Reinforce",
    gujarati: "મજબૂત કરવું",
    typeofWord: "verb",
    meaning: "To strengthen or support.",
    wordExample: {
      english: "China’s ban on rare earth technologies reinforces its dominance in the sector.",
      gujarati: "દુર્લભ પૃથ્વી ટેકનોલોજી પર ચીનના પ્રતિબંધથી તે ક્ષેત્રમાં તેનું વર્ચસ્વ મજબૂત થાય છે.",
    },
    synonyms: [
      { word: "Fortify", gujarati: "કિલ્લેબંધી કરવી / મજબૂત કરો" },
      { word: "Bolster", gujarati: "ટેકો આપવો" },
      { word: "Enhance", gujarati: "વધારવું / વૃદ્ધિ કરવી" },
      { word: "Amplify", gujarati: "વિસ્તૃત કરવું / પ્રસારવું" },
    ],
    antonyms: [
      { word: "Weaken", gujarati: "કમજોર કરવું" },
      { word: "Undermine", gujarati: "નીચેથી જમીન ખોદી કાઢવી / ઘસી નાખવું" },
      { word: "Diminish", gujarati: "ઘટાડવું" },
      { word: "Erode", gujarati: "કટાવ કરવો" },
    ],
  },
  {
    word: "Robust",
    gujarati: "મજબૂત",
    typeofWord: "adjective",
    meaning: "Strong and effective in all or most situations.",
    wordExample: {
      english: "Kazakhstan is building a robust rare earth extraction industry with international partnerships.",
      gujarati: "કઝાકિસ્તાન આંતરરાષ્ટ્રીય ભાગીદારીઓ સાથે એક મજબૂત દુર્લભ પૃથ્વી નિષ્કર્ષણ ઉદ્યોગ બનાવી રહ્યું છે.",
    },
    synonyms: [
      { word: "Sturdy", gujarati: "મજબૂત" },
      { word: "Resilient", gujarati: "લવચીક / શારીરિક કે માનસિક મૂળ સ્થિતિ પ્રાપ્ત કરનાર" },
      { word: "Vigorous", gujarati: "જોરદાર" },
      { word: "Durable", gujarati: "ટકાઉ" },
    ],
    antonyms: [
      { word: "Fragile", gujarati: "નાજુક" },
      { word: "Weak", gujarati: "કમજોર" },
      { word: "Delicate", gujarati: "નાજુક" },
      { word: "Feeble", gujarati: "દુર્બળ" },
    ],
  },
  {
    word: "Proximity",
    gujarati: "નિકટતા",
    typeofWord: "noun",
    meaning: "Nearness in space, time, or relationship.",
    wordExample: {
      english: "Kazakhstan’s proximity to India makes it a favorable partner for rare earth imports.",
      gujarati: "કઝાકિસ્તાનની ભારત સાથેની નિકટતા તેને દુર્લભ પૃથ્વી આયાત માટે એક અનુકૂળ ભાગીદાર બનાવે છે.",
    },
    synonyms: [
      { word: "Closeness", gujarati: "નિકટતા" },
      { word: "Nearness", gujarati: "નિકટતા" },
      { word: "Adjacency", gujarati: "સંલગ્નતા / જોડેનું" },
      { word: "Vicinity", gujarati: "સાન્નિધ્ય / આસપાસ / નજીકમાં" },
    ],
    antonyms: [
      { word: "Distance", gujarati: "અંતર" },
      { word: "Remoteness", gujarati: "દૂરસ્થતા" },
      { word: "Separation", gujarati: "અલગાવ / વિભાજન / જુદાઈ" },
      { word: "Isolation", gujarati: "એકલતા" },
    ],
  },
  {
    word: "Dissent",
    gujarati: "અસંમતિ", 
    typeofWord: "noun",
    meaning: "Holding or expressing an opinion different from the majority.",
    wordExample: {
      english: "The judge’s dissent highlighted an alternate perspective on the case.",
      gujarati: "ન્યાયાધીશની અસંમતિએ કેસ પર એક વૈકલ્પિક દ્રષ્ટિકોણ પર પ્રકાશ પાડ્યો.", 
    },
    synonyms: [
      { word: "Disagreement", gujarati: "અસંમતિ" },
      { word: "Opposition", gujarati: "વિરોધ" },
      { word: "Objection", gujarati: "વાંધો" },
    ],
    antonyms: [
      { word: "Agreement", gujarati: "સંમતિ" },
      { word: "Consensus", gujarati: "સર્વાનુમતિ" },
      { word: "Harmony", gujarati: "સુમેળ / સામંજસ્યપૂર્ણ" },
    ],
  },
  {
    word: "Edifice",
    gujarati: "સંરચના / ઇમારત / માળખું", 
    typeofWord: "noun",
    meaning: "A large and imposing structure; often metaphorically referring to a complex system.",
    wordExample: {
      english: "The edifice of modern education relies on both traditional and digital teaching methods.",
      gujarati: "આધુનિક શિક્ષણની ઇમારત પરંપરાગત અને ડિજિટલ શિક્ષણ પદ્ધતિઓ બંને પર આધારિત છે.", 
    },
    synonyms: [
      { word: "Structure", gujarati: "રચના / માળખું" },
      { word: "Building", gujarati: "ઈમારત" },
      { word: "Framework", gujarati: "ઢાંચો" },
    ],
    antonyms: [
      { word: "Ruin", gujarati: "બરબાદી / વિનાશ" },
      { word: "Dismantlement", gujarati: "વિખેડો / વિખેરી નાખવું" },
    ],
  },
  {
    word: "Invincible",
    gujarati: "અજેય", 
    typeofWord: "adjective",
    meaning: "Too powerful to be defeated or overcome.",
    wordExample: {
      english: "The team appeared invincible throughout the tournament, winning all their matches.",
      gujarati: "ટુર્નામેન્ટ દરમિયાન ટીમ અજેય લાગતી હતી, તેણે તેની બધી મેચ જીતી હતી.", 
    },
    synonyms: [
      { word: "Unbeatable", gujarati: "અજેય" },
      { word: "Invulnerable", gujarati: "અવિનાશી" },
      { word: "Indomitable", gujarati: "અદમ્ય" },
    ],
    antonyms: [
      { word: "Vulnerable", gujarati: "નિર્બળ" },
      { word: "Weak", gujarati: "કમજોર" },
      { word: "Conquerable", gujarati: "જીતી શકાય તેવું" },
    ],
  },
  {
    word: "Exhibit",
    gujarati: "પ્રદર્શન કરવું", 
    typeofWord: "verb",
    meaning: "To show or display something.",
    wordExample: {
      english: "The museum exhibits various artifacts from ancient civilizations.",
      gujarati: "સંગ્રહાલય પ્રાચીન સંસ્કૃતિઓની વિવિધ કલાકૃતિઓ પ્રદર્શિત કરે છે.", 
    },
    synonyms: [
      { word: "Display", gujarati: "દર્શાવવું" },
      { word: "Reveal", gujarati: "પ્રગટ કરવું" },
      { word: "Demonstrate", gujarati: "દર્શાવવું" },
    ],
    antonyms: [
      { word: "Conceal", gujarati: "છુપાવવું" },
      { word: "Hide", gujarati: "છુપાવવું" },
      { word: "Withhold", gujarati: "રોકવું" },
    ],
  },
  {
    word: "Capitulation",
    gujarati: "આત્મસમર્પણ / શરણાગતિ", 
    typeofWord: "noun",
    meaning: "The action of surrendering or ceasing to resist an opponent.",
    wordExample: {
      english: "The team’s early capitulation in the game left the fans disappointed.",
      gujarati: "રમતમાં ટીમના વહેલા આત્મસમર્પણથી ચાહકો નિરાશ થયા હતા.", 
    },
    synonyms: [
      { word: "Surrender", gujarati: "આત્મસમર્પણ" },
      { word: "Submission", gujarati: "નિવેદન" },
      { word: "Yield", gujarati: "વશ થવું" },
    ],
    antonyms: [
      { word: "Resistance", gujarati: "પ્રતિકાર" },
      { word: "Defiance", gujarati: "વિરોધ" },
      { word: "Opposition", gujarati: "વિરોધ" },
    ],
  },
  {
    word: "Leash",
    gujarati: "કાબૂમાં રાખવું / નિયંત્રણ", 
    typeofWord: "noun",
    meaning: "A restraint or control over something.",
    wordExample: {
      english: "The company kept a tight leash on expenses to stay within budget.",
      gujarati: "કંપની બજેટમાં રહેવા માટે ખર્ચ પર કડક નિયંત્રણ રાખતી હતી.", 
    },
    synonyms: [
      { word: "Control", gujarati: "નિયંત્રણ" },
      { word: "Restriction", gujarati: "નિયંત્રણ" },
      { word: "Tether", gujarati: "બાંધવું" },
    ],
    antonyms: [
      { word: "Freedom", gujarati: "સ્વતંત્રતા" },
      { word: "Release", gujarati: "મુક્તિ" },
      { word: "Liberation", gujarati: "મુક્તિ" },
    ],
  },
  {
    word: "Benign",
    gujarati: "દયાળુ", 
    typeofWord: "adjective",
    meaning: "Gentle and kind; not harmful in effect.",
    wordExample: {
      english: "The teacher's benign attitude made the students feel comfortable in class.",
      gujarati: "શિક્ષકના દયાળુ વલણથી વિદ્યાર્થીઓ વર્ગમાં આરામદાયક અનુભવતા હતા.", 
    },
    synonyms: [
      { word: "Kind", gujarati: "દયાળુ" },
      { word: "Gentle", gujarati: "કોમળ / સૌમ્ય / શાન્ત" },
      { word: "Benevolent", gujarati: "પરોપકારી" },
    ],
    antonyms: [
      { word: "Harsh", gujarati: "કઠોર" },
      { word: "Cruel", gujarati: "ક્રૂર" },
      { word: "Malevolent", gujarati: "દુષ્ટ" },
    ],
  },
  {
    word: "Permeate",
    gujarati: "વ્યાપી જવું", 
    typeofWord: "verb",
    meaning: "To spread throughout something.",
    wordExample: {
      english: "The smell of freshly baked bread permeated the entire house.",
      gujarati: "તાજી શેકેલી બ્રેડની સુગંધ આખા ઘરમાં વ્યાપી ગઈ હતી.", 
    },
    synonyms: [
      { word: "Penetrate", gujarati: "ભેદવું / ઘૂસી જવું / પેસવું" },
      { word: "Saturate", gujarati: "સંતૃપ્ત કરવું" },
      { word: "Diffuse", gujarati: "વિસરવું" },
    ],
    antonyms: [
      { word: "Contain", gujarati: "રોકવું / સમાવેશ કરવો" },
      { word: "Limit", gujarati: "મર્યાદિત કરવું" },
      { word: "Restrict", gujarati: "નિયંત્રિત કરવું" },
    ],
  },
  {
    word: "Exorbitant",
    gujarati: "અતિશય / મોંઘું", 
    typeofWord: "adjective",
    meaning: "Unreasonably high in price or cost.",
    wordExample: {
      english: "The restaurant was criticized for its exorbitant prices.",
      gujarati: "રેસ્ટોરન્ટને તેના અતિશય મોંઘા ભાવો માટે ટીકા કરવામાં આવી હતી.", 
    },
    synonyms: [
      { word: "Excessive", gujarati: "અતિશય" },
      { word: "Outrageous", gujarati: "અતિશય" },
      { word: "Overpriced", gujarati: "મોંઘું" },
    ],
    antonyms: [
      { word: "Reasonable", gujarati: "વાજબી" },
      { word: "Moderate", gujarati: "મધ્યમ" },
      { word: "Affordable", gujarati: "સસ્તું" },
    ],
  },
  {
    word: "Discrete",
    gujarati: "અલગ", 
    typeofWord: "adjective",
    meaning: "Individually separate and distinct.",
    wordExample: {
      english: "The report divided the data into discrete categories for easier analysis.",
      gujarati: "રિપોર્ટે સરળ વિશ્લેષણ માટે ડેટાને અલગ શ્રેણીઓમાં વહેંચ્યો હતો.", 
    },
    synonyms: [
      { word: "Distinct", gujarati: "અલગ" },
      { word: "Separate", gujarati: "અલગ" },
      { word: "Independent", gujarati: "સ્વતંત્ર" },
    ],
    antonyms: [
      { word: "Connected", gujarati: "જોડાયેલ" },
      { word: "Continuous", gujarati: "નિરંતર" },
      { word: "Unified", gujarati: "એકીકૃત" },
    ],
  },
  {
    word: "Obsolete",
    gujarati: "અપ્રચલિત / પુરાતન / લુપ્ત", 
    typeofWord: "adjective",
    meaning: "No longer in use; out of date.",
    wordExample: {
      english: "Many technological devices from the 1990s are now considered obsolete.",
      gujarati: "1990 ના દાયકાના ઘણા ટેકનોલોજીકલ ઉપકરણો હવે પુરાતન ગણાય છે.", 
    },
    synonyms: [
      { word: "Outdated", gujarati: "જૂનું" },
      { word: "Archaic", gujarati: "પ્રાચીન" },
      { word: "Antiquated", gujarati: "પુરાતન" },
    ],
    antonyms: [
      { word: "Modern", gujarati: "આધુનિક" },
      { word: "Current", gujarati: "વર્તમાન" },
      { word: "Updated", gujarati: "અપડેટ કરેલ" },
    ],
  },
  {
    word: "Intrusion",
    gujarati: "અતિક્રમણ / ઘુસણખોરી / અનાધિકાર પ્રવેશ", 
    typeofWord: "noun",
    meaning: "The act of entering a place or situation where one is unwelcome or uninvited.",
    wordExample: {
      english: "The journalist apologized for the intrusion into the celebrity's personal life.",
      gujarati: "પત્રકારે સેલિબ્રિટીના ખાનગી જીવનમાં અતિક્રમણ કરવા બદલ માફી માંગી હતી.", 
    },
    synonyms: [
      { word: "Encroachment", gujarati: "અતિક્રમણ" },
      { word: "Invasion", gujarati: "આક્રમણ" },
      { word: "Interference", gujarati: "હસ્તક્ષેપ" },
    ],
    antonyms: [
      { word: "Withdrawal", gujarati: "પાછો ખેંચવો" },
      { word: "Retreat", gujarati: "વાપસી" },
      { word: "Exclusion", gujarati: "બાકાત" },
    ],
  },
  {
    word: "Impediment",
    gujarati: "અવરોધ", 
    typeofWord: "noun",
    meaning: "A hindrance or obstruction in doing something.",
    wordExample: {
      english: "Poor internet connectivity was a major impediment to remote learning.",
      gujarati: "ખરાબ ઇન્ટરનેટ કનેક્ટિવિટી દૂરસ્થ શિક્ષણ માટે મુખ્ય અવરોધ હતો.", 
    },
    synonyms: [
      { word: "Obstacle", gujarati: "અવરોધ" },
      { word: "Barrier", gujarati: "અવરોધ" },
      { word: "Limitation", gujarati: "મર્યાદા" },
      { word: "hindrance", gujarati: "અવરોધ / અડચણ" },
    ],
    antonyms: [
      { word: "Aid", gujarati: "સહાય" },
      { word: "Assistance", gujarati: "સહાય" },
      { word: "Support", gujarati: "ટેકો" },
    ],
  },
  {
    word: "Coerce",
    gujarati: "દબાણ કરવું", 
    typeofWord: "verb",
    meaning: "To persuade someone to do something by using force or threats.",
    wordExample: {
      english: "The kidnappers tried to coerce the victim into signing over his property.",
      gujarati: "અપહરણકર્તાઓએ પીડિતને તેની મિલકત પર હસ્તાક્ષર કરવા દબાણ કરવાનો પ્રયાસ કર્યો હતો.", 
    },
    synonyms: [
      { word: "Compel", gujarati: "દબાણ કરવું" },
      { word: "Force", gujarati: "દબાણ કરવું" },
      { word: "Intimidate", gujarati: "ડરાવવું" },
    ],
    antonyms: [
      { word: "Persuade", gujarati: "સમજાવવું" },
      { word: "Encourage", gujarati: "પ્રોત્સાહિત કરવું" },
      { word: "Convince", gujarati: "સમજાવવું" },
    ],
  },
  {
    word: "Plummet",
    gujarati: "ઘટવું / ધડાધડ પડવું", 
    typeofWord: "verb",
    meaning: "To fall or drop straight down at high speed.",
    wordExample: {
      english: "The company's stock price plummeted after the scandal was exposed.",
      gujarati: "કૌભાંડ બહાર આવ્યા બાદ કંપનીના શેરનો ભાવ ધડાધડ પડ્યો હતો.", 
    },
    synonyms: [
      { word: "Decline", gujarati: "ઘટાડો / નીચું પડવું / નકાર" },
      { word: "Fall", gujarati: "પડવું" },
      { word: "Tumble", gujarati: "લથડવું" },
    ],
    antonyms: [
      { word: "Rise", gujarati: "વધવું" },
      { word: "Ascend", gujarati: "ઉપર જવું" },
      { word: "Increase", gujarati: "વધવું" },
    ],
  },
  {
    word: "Typecast",
    gujarati: "સાચો પાત્ર આપવો", 
    typeofWord: "verb",
    meaning: "To assign someone a role or attribute that restricts them to a narrow scope.",
    wordExample: {
      english: "The actor was typecast as a villain after playing similar roles in several movies.",
      gujarati: "અભિનેતાને અનેક ફિલ્મોમાં સમાન ભૂમિકા ભજવ્યા પછી ખલનાયક તરીકે સાચો પાત્ર આપવામાં આવ્યો હતો.", 
    },
    synonyms: [
      { word: "Stereotype", gujarati: "રૂઢિબદ્ધ ખ્યાલ" },
      { word: "Categorize", gujarati: "વર્ગીકૃત કરવું" },
      { word: "Label", gujarati: "લેબલ લગાવવું" },
    ],
    antonyms: [
      { word: "Diversify", gujarati: "વિવિધ બનાવવું" },
      { word: "Liberate", gujarati: "મુક્ત કરવું" },
      { word: "Differentiate", gujarati: "અલગ પાડવું" },
    ],
  },
  {
    word: "Forbearance",
    gujarati: "ધીરજ", 
    typeofWord: "noun",
    meaning: "Patient self-control; restraint and tolerance.",
    wordExample: {
      english: "The landlord showed forbearance by giving the tenant extra time to pay the rent.",
      gujarati: "જમીનમાલિકે ભાડુ ઉઘરાવવા માટે ભાડુઆતને વધારાનો સમય આપીને ધીરજ દર્શાવી હતી.", 
    },
    synonyms: [
      { word: "Patience", gujarati: "ધીરજ" },
      { word: "Endurance", gujarati: "સહનશક્તિ" },
      { word: "Tolerance", gujarati: "સહિષ્ણુતા" },
    ],
    antonyms: [
      { word: "Impatience", gujarati: "અધીરાઈ" },
      { word: "Agitation", gujarati: "ચિંતા / ઉત્તેજિત" },
      { word: "Frustration", gujarati: "નિરાશા / હતાશા" },
    ],
  },
  {
    word: "Renege",
    gujarati: "વાપસી લેવી", 
    typeofWord: "verb",
    meaning: "To go back on a promise, undertaking, or contract.",
    wordExample: {
      english: "The company reneged on its agreement to provide free healthcare for employees.",
      gujarati: "કંપનીએ કર્મચારીઓને મફત આરોગ્ય સંભાળ પૂરી પાડવાની તેની કરાર પરથી વાપસી લીધી હતી.", 
    },
    synonyms: [
      { word: "Break", gujarati: "તોડવું" },
      { word: "Default", gujarati: "કબૂલાત ન પાળવી" },
      { word: "Backtrack", gujarati: "વાપસી લેવી" },
    ],
    antonyms: [
      { word: "Fulfill", gujarati: "પૂર્ણ કરવું" },
      { word: "Honor", gujarati: "માન આપવું" },
      { word: "Adhere", gujarati: "પાલન કરવું" },
    ],
  },
  {
    word: "Wake-up call",
    gujarati: "જાગૃતિ", 
    typeofWord: "noun",
    meaning: "An event or situation that alerts one to a problem that needs immediate attention.",
    wordExample: {
      english: "The near-miss car accident was a wake-up call for her to drive more cautiously.",
      gujarati: "નજીકમાં થયેલો કાર અકસ્માત તેણીને વધુ સાવધાનીપૂર્વક વાહન ચલાવવા માટે એક જાગૃત કોલ હતો.", 
    },
    synonyms: [
      { word: "Warning", gujarati: "ચેતવણી" },
      { word: "Red flag", gujarati: "લાલ ધ્વજ" },
      { word: "Alert", gujarati: "ચેતવણી" },
    ],
    antonyms: [
      { word: "Ignorance", gujarati: "અજ્ઞાન" },
      { word: "Oversight", gujarati: "દેખરેખ / ધ્યાનચૂક" },
      { word: "Inattention", gujarati: "અવગણના" },
    ],
  },
  {
    word: "Apportion",
    gujarati: "વહેંચવું", 
    typeofWord: "verb",
    meaning: "To divide and allocate responsibility or blame.",
    wordExample: {
      english: "The profits were apportioned among the partners according to their investments.",
      gujarati: "નફો ભાગીદારો વચ્ચે તેમના રોકાણો અનુસાર વહેંચવામાં આવ્યો હતો.", 
    },
    synonyms: [
      { word: "Assign", gujarati: "નિયુક્ત કરવું" },
      { word: "Distribute", gujarati: "વહેંચવું" },
      { word: "Allocate", gujarati: "આયોજન કરવું / વહેંચી આપવું" },
    ],
    antonyms: [
      { word: "Combine", gujarati: "જોડવું" },
      { word: "Unify", gujarati: "એકીકૃત કરવું" },
      { word: "Withhold", gujarati: "રોકવું" },
    ],
  },
  {
    word: "Threshold",
    gujarati: "સીમા", 
    typeofWord: "noun",
    meaning: "The starting point of an experience, event, or capacity.",
    wordExample: {
      english: "She has a low threshold for pain, so she avoids extreme physical activities.",
      gujarati: "તેણીને પીડા માટે સહનશક્તિ ઓછી છે, તેથી તે તીવ્ર શારીરિક પ્રવૃત્તિઓથી દૂર રહે છે.", 
    },
    synonyms: [
      { word: "Boundary", gujarati: "સીમા" },
      { word: "Brink", gujarati: "કિનારો" },
      { word: "Verge", gujarati: "કિનારો" },
    ],
    antonyms: [
      { word: "End", gujarati: "અંત" },
      { word: "Conclusion", gujarati: "નિષ્કર્ષ" },
      { word: "Closure", gujarati: "સમાપ્તિ" },
    ],
  },
  {
    word: "Complacency",
    gujarati: "આત્મસંતોષ / અહંકાર", 
    typeofWord: "noun",
    meaning: "A feeling of smug satisfaction with oneself or one's achievements, often unaware of danger.",
    wordExample: {
      english: "The team’s complacency after winning the first game led to their defeat in the next.",
      gujarati: "પ્રથમ ગેમ જીત્યા બાદ ટીમની આત્મસંતુષ્ટિ પછીની મેચમાં તેમની હાર તરફ દોરી ગઈ.", 
    },
    synonyms: [
      { word: "Self-satisfaction", gujarati: "આત્મતૃપ્તિ" },
      { word: "Overconfidence", gujarati: "અતિઆત્મવિશ્વાસ" },
      { word: "Negligence", gujarati: "બેદરકારી" },
    ],
    antonyms: [
      { word: "Vigilance", gujarati: "સાવધાની" },
      { word: "Awareness", gujarati: "જાગૃતિ" },
      { word: "Concern", gujarati: "ચિંતા" },
    ],
  },
  {
    word: "Pitfall",
    gujarati: "મુશ્કેલી / ખાબોચિયું", 
    typeofWord: "noun",
    meaning: "A hidden or unsuspected danger or difficulty.",
    wordExample: {
      english: "One of the pitfalls of online shopping is the risk of falling for scams.",
      gujarati: "ઓનલાઈન શોપિંગની ખામીઓમાંની એક છે છેતરપિંડીનો ભોગ બનવાનું જોખમ.", 
    },
    synonyms: [
      { word: "Hazard", gujarati: "જોખમ" },
      { word: "Trap", gujarati: "જાળ" },
      { word: "Drawback", gujarati: "અવગુણ / ખામી" },
    ],
    antonyms: [
      { word: "Safety", gujarati: "સલામતી" },
      { word: "Advantage", gujarati: "લાભ" },
      { word: "Benefit", gujarati: "લાભ" },
    ],
  },
  {
    word: "Utterance",
    gujarati: "ઉચ્ચારણ", 
    typeofWord: "noun",
    meaning: "A spoken word, statement, or vocal sound.",
    wordExample: {
      english: "His utterance of the phrase 'I’m sorry' was barely audible.",
      gujarati: "તેમનું 'મને માફ કરો' વાક્યનું ઉચ્ચારણ અસ્પષ્ટ હતું.", 
    },
    synonyms: [
      { word: "Remark", gujarati: "ટિપ્પણી" },
      { word: "Expression", gujarati: "અભિવ્યક્તિ" },
      { word: "Declaration", gujarati: "ઘોષણા" },
    ],
    antonyms: [
      { word: "Silence", gujarati: "મૌન" },
      { word: "Secrecy", gujarati: "ગુપ્તતા" },
    ] 
  },
  {
    word: "Ruinous",
    gujarati: "વિનાશક", 
    typeofWord: "adjective",
    meaning: "Involving or causing sudden great damage or suffering.",
    wordExample: {
      english: "The company’s ruinous decision to expand too quickly led to bankruptcy.",
      gujarati: "કંપનીનો ખૂબ જ ઝડપથી વિસ્તરણ કરવાનો વિનાશક નિર્ણય દિવાળિયાપણા તરફ દોરી ગયો.", 
    },
    synonyms: [
      { word: "Disastrous", gujarati: "વિનાશક" },
      { word: "Calamitous", gujarati: "વિપત્તિજનક" },
    ],
    antonyms: [
      { word: "Fortunate", gujarati: "ભાગ્યશાળી / લાભદાયી" },
      { word: "Favorable", gujarati: "અનુકૂળ" },
      { word: "Harmless", gujarati: "સુરક્ષિત" },
    ],
  },
  {
    word: "Tumultuous",
    gujarati: "ઉથલપાથલવાળું / તોફાની", 
    typeofWord: "adjective",
    meaning: "Characterized by disorder, confusion, or turbulence.",
    wordExample: {
      english: "The stock market experienced a tumultuous week with significant fluctuations.",
      gujarati: "શેરબજારે નોંધપાત્ર વધઘટ સાથે ઉથલપાથલવાળો અઠવાડિયાનો અનુભવ થયો હતો.", 
    },
    synonyms: [
      { word: "Turbulent", gujarati: "ઉથલપાથલવાળું" },
      { word: "Chaotic", gujarati: "અવ્યવસ્થિત / અસ્તવ્યસ્ત" },
      { word: "Stormy", gujarati: "વાવાઝોડાયુક્ત" },
    ],
    antonyms: [
      { word: "Calm", gujarati: "શાંત" },
      { word: "Peaceful", gujarati: "શાંતિપૂર્ણ" },
      { word: "Stable", gujarati: "સ્થિર" },
    ],
  },
  {
    word: "Stem",
    gujarati: "રોકવું", 
    typeofWord: "verb",
    meaning: "To stop or restrict the flow or growth of something.",
    wordExample: {
      english: "The government introduced measures to stem the rising inflation.",
      gujarati: "વધતી જતી મોંઘવારીને રોકવા માટે સરકારે પગલાં લીધાં છે.", 
    },
    synonyms: [
      { word: "Halt", gujarati: "રોકવું" },
      { word: "Restraint", gujarati: "નિયંત્રણ" },
      { word: "Curtail", gujarati: "ઘટાડવુ / કાપ મૂકવો" },
    ],
    antonyms: [
      { word: "Encourage", gujarati: "પ્રોત્સાહિત કરવું" },
      { word: "Foster", gujarati: "ઉછેરવું" },
      { word: "Promote", gujarati: "પ્રોત્સાહિત કરવું" },
    ],
  },
  {
    word: "Precariously",
    gujarati: "અસ્થિર રીતે", 
    typeofWord: "adverb", 
    meaning: "In a way that is not securely held or in a position likely to collapse.",
    wordExample: {
      english: "The climber stood precariously on the edge of the cliff.",
      gujarati: "ચડનાર ખડકની ધાર પર અસ્થિર રીતે ઊભો હતો.", 
    },
    synonyms: [
      { word: "Unsteadily", gujarati: "અસ્થિર રીતે" },
      { word: "Insecurely", gujarati: "અસુરક્ષિત રીતે" },
      { word: "Dangerously", gujarati: "ખતરનાક રીતે" },
    ],
    antonyms: [
      { word: "Securely", gujarati: "સુરક્ષિત રીતે" },
      { word: "Safely", gujarati: "સુરક્ષિત રીતે" },
      { word: "Steadily", gujarati: "સ્થિર રીતે" },
    ],
  },
  {
    word: "Sputtering",
    gujarati: "ઠોકરા મારતાં / ઝટકો મારતાં", 
    typeofWord: "adverb", 
    meaning: "Making a series of soft explosive sounds; working in a way that shows inconsistency.",
    wordExample: {
      english: "The old car started sputtering as it climbed the steep hill.",
      gujarati: "જૂની કાર ઢોળાવવાળા ટેકરા પર ચઢતી વખતે ઠોકરા મારવા લાગી.", 
    },
    synonyms: [
      { word: "Stumbling", gujarati: "લથડતા ચાલવું / ઠોકર ખાવી" },
      { word: "Faltering", gujarati: "લથડતા / અચકાતું" },
      { word: "Stammering", gujarati: "હકળતા / અચકાતાં અચકાતાં બોલવું" },
    ],
    antonyms: [
      { word: "Flowing", gujarati: "વહેતા" },
      { word: "Smooth", gujarati: "સરળ" },
      { word: "Consistent", gujarati: "સુસંગત" },
    ],
  },
  {
    word: "Inevitability",
    gujarati: "અનિવાર્યતા", 
    typeofWord: "noun",
    meaning: "The quality of being certain to happen.",
    wordExample: {
      english: "The inevitability of change is a constant in life.",
      gujarati: "જીવનમાં પરિવર્તનની અનિવાર્યતા એ એક સતત વાસ્તવિકતા છે.", 
    },
    synonyms: [
      { word: "Certainty", gujarati: "નિશ્ચિતતા" },
      { word: "Necessity", gujarati: "આવશ્યકતા" },
      { word: "Surety", gujarati: "નિશ્ચિતતા" },
    ],
    antonyms: [
      { word: "Uncertainty", gujarati: "અનિશ્ચિતતા" },
      { word: "Doubt", gujarati: "શંકા" },
      { word: "Improbability", gujarati: "અસંભવિતતા" },
    ],
  },
  {
    word: "Quibble",
    gujarati: "વાંધો ઉઠાવવો / બકવાસ કરવી / ઝગડવું / કટાક્ષ", 
    typeofWord: "verb",
    meaning: "A slight objection or criticism about a trivial matter.",
    wordExample: {
      english: "They quibbled over the color of the curtains instead of focusing on the renovation plan.",
      gujarati: "તેઓએ સમારકામની યોજના પર ધ્યાન કેન્દ્રિત કરવાને બદલે પડદાના રંગ અંગે બકવાસ/કટાક્ષ કરતા હતા.", 
    },
    synonyms: [
      { word: "Nitpick", gujarati: "ખામી શોધવી" },
      { word: "Cavil", gujarati: "વાંધો ઉઠાવવો" },
      { word: "Fuss", gujarati: "ધમાલ / નજીવી બાબતની મોટી પંચાત / ગડબડ" },
    ],
    antonyms: [
      { word: "Agree", gujarati: "સંમત થવું" },
      { word: "Accept", gujarati: "સ્વીકારવું" },
      { word: "Commend", gujarati: "સરાહના કરવી / વખાણવું" },
    ],
  },
  {
    word: "Foray",
    gujarati: "અચાનક હુમલો / પ્રયાસ", 
    typeofWord: "noun",
    meaning: "A sudden attack or incursion; an initial venture into a new field.",
    wordExample: {
      english: "His foray into entrepreneurship proved to be highly successful.",
      gujarati: "ઉદ્યોગસાહસિકતામાં તેમનો પ્રારંભિક પ્રયાસ ખૂબ જ સફળ સાબિત થયો.", 
    },
    synonyms: [
      { word: "Raid", gujarati: "દરોડો" },
      { word: "Expedition", gujarati: "અભિયાન" },
      { word: "Attempt", gujarati: "પ્રયાસ" },
    ],
    antonyms: [
      { word: "Retreat", gujarati: "વાપસી" },
      { word: "Withdrawal", gujarati: "પાછો ખેંચવો" },
    ],
  },
  {
    word: "Purveyor",
    gujarati: "પુરવઠાકાર / પ્રદાતા / આપનાર", 
    typeofWord: "noun",
    meaning: "A person or group that supplies goods or services.",
    wordExample: {
      english: "The purveyor of quality chess equipment was a key supporter of the tournament.",
      gujarati: "ઉચ્ચ ગુણવત્તાવાળા ચેસ સાધનોનો પ્રદાતા ટુર્નામેન્ટનો મુખ્ય સમર્થક હતો.", 
    },
    synonyms: [
      { word: "Supplier", gujarati: "પુરવઠાકાર" },
      { word: "Vendor", gujarati: "વિક્રેતા / વેચનાર" },
      { word: "Provider", gujarati: "પ્રદાતા" },
    ],
    antonyms: [
      { word: "Consumer", gujarati: "ગ્રાહક" },
      { word: "Buyer", gujarati: "ખરીદદાર" },
    ],
  },
  {
    word: "Confluence",
    gujarati: "સંગમ", 
    typeofWord: "noun",
    meaning: "The junction of two or more things, especially rivers or ideas.",
    wordExample: {
      english: "A confluence of factors led to the company’s unprecedented success.",
      gujarati: "કંપનીની અભૂતપૂર્વ સફળતા માટે પરિબળોનો સંગમ જવાબદાર હતો.", 
    },
    synonyms: [
      { word: "Convergence", gujarati: "સંકલન" },
      { word: "Union", gujarati: "એકતા / ભેગા થવું" },
      { word: "Meeting", gujarati: "મુલાકાત / મળવું" },
    ],
    antonyms: [
      { word: "Divergence", gujarati: "વિચલન / અંતર / જુદા પડવું" },
      { word: "Separation", gujarati: "અલગાવ / વિયોગ / જુદાઈ" },
    ],
  },
  {
    word: "Unequivocal",
    gujarati: "સ્પષ્ટ", 
    typeofWord: "adjective",
    meaning: "Leaving no doubt; unambiguous.",
    wordExample: {
      english: "The minister’s speech was an unequivocal declaration of support for the new policy.",
      gujarati: "મંત્રીનું ભાષણ નવી નીતિ માટે સમર્થનની સ્પષ્ટ ઘોષણા હતું.", 
    },
    synonyms: [
      { word: "Clear", gujarati: "સ્પષ્ટ" },
      { word: "Unmistakable", gujarati: "સ્પષ્ટ" },
      { word: "Categorical", gujarati: "વર્ગીકૃત / સુસ્પષ્ટ" },
    ],
    antonyms: [
      { word: "Ambiguous", gujarati: "અસ્પષ્ટ" },
      { word: "Uncertain", gujarati: "અનિશ્ચિત" },
      { word: "Unclear", gujarati: "અસ્પષ્ટ" },
    ],
  },
  // ... other verbs
];